import type {Branch} from "@/types/branch";

export  const mockBranches: Branch[] = [
    {
        id: 1,
        branchCode: "BR-0001",
        name: "Head Office",
        type: "head_office",
        manager: "James Banda",
        phone: "+265 888 123 456",
        email: "headoffice@company.com",
        location: "Blantyre",
        activeClients:40,
        activeLoans:36,
        status: "active",
    },
    {
        id: 2,
        branchCode: "BR-0002",
        name: "Lilongwe Branch",
        type: "branch",
        manager: "Grace Phiri",
        phone: "+265 999 234 567",
        email: "lilongwe@company.com",
        location: "Lilongwe",
        activeClients:40,
        activeLoans:36,
        status: "active",
    },
    {
        id: 3,
        branchCode: "BR-0003",
        name: "Mzuzu Branch",
        type: "branch",
        manager: "Peter Mbewe",
        phone: "+265 888 345 678",
        email: "mzuzu@company.com",
        location: "Mzuzu",
        activeClients:40,
        activeLoans:36,
        status: "active",
    },
    {
        id: 4,
        branchCode: "BR-0004",
        name: "Zomba Branch",
        type: "branch",
        manager: "Mary Chirwa",
        phone: "+265 999 456 789",
        email: "zomba@company.com",
        location: "Zomba",
        activeClients:40,
        activeLoans:36,
        status: "active",
    },
    {
        id: 5,
        branchCode: "BR-0005",
        name: "Mangochi Branch",
        type: "regional",
        manager: "Andrew Kumwenda",
        phone: "+265 888 567 890",
        email: "mangochi@company.com",
        location: "Mangochi",
        activeClients:40,
        activeLoans:36,
        status: "inactive",
    },
];